#!/bin/bash
#SBATCH --partition=normal
#SBATCH --constraint=silver_4110
#SBATCH --nodes 1
#SBATCH -t 8:00:00
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=l.lan@vu.nl
LANG=en_US.UTF-8

module load 2021
module load Python/3.9.5-GCCcore-10.3.0

echo start of job
poetry run python -m tree_partitioning.transient_stability --time_limit 1200 --min_size 600 --max_size 2300 --n_clusters 6 --results_path 600-2300.txt
echo end of job
