#!/bin/bash
#SBATCH --partition=normal
#SBATCH --constraint=silver_4110
#SBATCH --nodes 1
#SBATCH -t 8:00:00
#SBATCH --mail-type=BEGIN,END
LANG=en_US.UTF-8
module load 2020
module load Gurobi/9.1.1-foss-2020a-Python-3.8.2

module load 2021
module load Python/3.9.5-GCCcore-10.3.0

echo start of job
poetry run python experiments/power_flow_disruption.py --time_limit 600 --min_size 600 --max_size 2300 --max_clusters 5
echo end of job
