#!/bin/bash
#SBATCH --partition=normal
#SBATCH --constraint=gold_6130
#SBATCH --nodes 1
#SBATCH -t 18:00:00
#SBATCH --mail=l.lan@vu.nl
#SBATCH --mail-type=BEGIN,END
LANG=en_US.UTF-8

module load 2020
module load Gurobi/9.1.1-foss-2020a-Python-3.8.2

module load 2021
module load Python/3.9.5-GCCcore-10.3.0

echo start of job
poetry run python experiments/cascading_failure.py --time_limit 600 --max_size 3000 --max_clusters 5 --gci_weight $1 --results_dir $2
echo end of job
